### ISSUE TITLE
TypeError: ('__init__() takes at least 3 arguments (1 given)', <class 'subprocess32.TimeoutExpired'>, ())

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#119]
Filing here, as this may be specific to our modifications to osm-export-tool2 (exception type is `subprocess32.TimeoutExpired`).

This occurred after the MBTiles task timed out. As a result, subsequent requests to check on the status of the associated task return 500s.

```
[10/Mar/2016 00:03:09] ERROR [django.request:284] Internal Server Error: /api/runs
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ubuntu/osm-export-tool2/api/views.py", line 421, in list
    return Response(serializer.data, status=status.HTTP_200_OK)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 674, in data
    ret = super(ListSerializer, self).data
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 239, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 614, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 472, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 614, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 472, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/fields.py", line 1645, in to_representation
    return method(value)
  File "/home/ubuntu/osm-export-tool2/api/serializers.py", line 184, in get_errors
    return serializer.data
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 674, in data
    ret = super(ListSerializer, self).data
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 239, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 614, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 472, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/fields.py", line 1645, in to_representation
    return method(value)
  File "/home/ubuntu/osm-export-tool2/api/serializers.py", line 150, in get_exception
    exc_info = cPickle.loads(str(obj.exception)).exc_info
TypeError: ('__init__() takes at least 3 arguments (1 given)', <class 'subprocess32.TimeoutExpired'>, ())
```

**Comment by mojodna** [comment]
See https://github.com/AmericanRedCross/posm-imagery-api/blob/master/app.py#L156-L162 for a work-around.
