### ISSUE TITLE
Post-process Overpass output for duplicate usernames

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#130]
See https://github.com/drolbr/Overpass-API/issues/257 for more information.

For the Huaquillas, EC bounding box, `Nodes&Roads` showed up with 2 separate user ids triggering foreign key errors when loading into the APIDB schema w/ Osmosis.

**Comment by mojodna** [comment]
```bash
#!/usr/bin/env bash

set -eo pipefail

if [[ "$1" == "" && "$2" == "" ]]; then
  >&2 echo "Usage: remap-userid.sh <uid> <user>"
  exit 1
fi

sed=$(which sed)
# use gsed if available
type gsed > /dev/null && sed=$(which gsed)

$sed -re "s/uid=\"$1\" user=\".+\"/uid=\"$1\" user=\"$2\"/"
```

**Comment by mojodna** [comment]
Practical usage: `cat huaquillas-201604071225.xml | ./remap-userid.sh 1708958 georhoko > huaquillas-201604071225-fixed.xml`

**Comment by mojodna** [comment]
Symptom:

```
org.openstreetmap.osmosis.core.OsmosisRuntimeException: Unable to insert user with id 1708958 into the database.
	at org.openstreetmap.osmosis.apidb.v0_6.impl.UserManager.insertUser(UserManager.java:143)
	at org.openstreetmap.osmosis.apidb.v0_6.impl.UserManager.addOrUpdateUser(UserManager.java:191)
	at org.openstreetmap.osmosis.apidb.v0_6.ApidbWriter.process(ApidbWriter.java:1098)
	at org.openstreetmap.osmosis.core.progress.v0_6.EntityProgressLogger.process(EntityProgressLogger.java:71)
	at org.openstreetmap.osmosis.xml.v0_6.impl.NodeElementProcessor.end(NodeElementProcessor.java:139)
	at org.openstreetmap.osmosis.xml.v0_6.impl.OsmHandler.endElement(OsmHandler.java:107)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
	at org.openstreetmap.osmosis.xml.v0_6.XmlReader.run(XmlReader.java:111)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_display_name_idx"
  Detail: Key (display_name)=(Nodes&Roads) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:366)
	at org.openstreetmap.osmosis.apidb.v0_6.impl.UserManager.insertUser(UserManager.java:140)
	... 18 more
```

**Comment by mojodna** [comment]
See also https://github.com/AmericanRedCross/posm-replay-tool/blob/c25d8e1/remap-userid.sh and https://github.com/AmericanRedCross/posm-replay-tool/blob/eb9c9bae4af940e9b436eca6390b691b828304a1/LOCAL.md#initialization (for diagnosis tips).

We have a process, though it's unclear how it fits into the initial data load, so I'm closing this until it rears its head again.
