### ISSUE TITLE
Unknown mapnik-reference version: '3.0.9'

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#23]
(Non-fatal error, but worth investigating the root cause.)

```
Error: Unknown mapnik-reference version: '3.0.9'
    at Object.module.exports.load (/usr/lib/node_modules/tessera/node_modules/tilelive-tmsource/node_modules/mapnik-reference/index.js:25:8)
    at Object.<anonymous> (/usr/lib/node_modules/tessera/node_modules/tilelive-tmsource/index.js:12:45)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /usr/lib/node_modules/tessera/lib/modules.js:12:13
    at Array.forEach (native)
Listening at http://:::8082/
```

**Comment by jflemer-ndp** [comment]
Yeah, I've seen that. Though as you mentioned it seems non impacting. I'll look into it (sometime).

**Comment by mojodna** [comment]
I can no longer reproduce this.
